config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos, only: [:index, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :name, length: {minimum: 4, maximum: 40 }, presence: true
  validates :image, attached: true,  content_type: [:png, :jpg, :jpeg]


  def uploader
    user.email.split('@').first || user.email
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ destroy ]
  http_basic_authenticate_with(
    name: Rails.application.credentials.dig(:login, :username),
    password: Rails.application.credentials.dig(:login, :password),
  ) if Rails.env.production?
  before_action :authenticate_user!, only: %i[new create destroy]

  # GET /photos or /photos.json
  def index

    sort_column = params[:sort] || "created_at"
    if sort_column == "name"
      sort_column = 'LOWER(name)'
    end
    sort_direction = params[:direction].presence_in(%w[asc desc]) || "desc"

    @photos = Photo.with_attached_image.includes(:user).order("#{sort_column} #{sort_direction}").page(params[:page]).per(10)
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_url, notice: "Photo was successfully created." }
        format.json { render json: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def photo_params
    params.require(:photo).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable_table_header(title, column, path_method, **)
    content_tag(:th, class: "th") do
      sortable_column(title, column, path_method)
    end
  end

  def sortable_column(title, column, path_method, **)
    direction = (column.to_s == params[:sort].to_s && params[:direction] == "asc") ? "desc" : "asc"

    query_params = request.query_parameters.merge(sort: column, direction: direction)

    path = send(path_method, query_params)
    link_to(path, class: "th-link", **) do
      concat title
      concat sort_icon(column)
    end
  end

  def sort_icon(column)
    return unless params[:sort].to_s == column.to_s

    if params[:direction] == "asc"
      content_tag(:i, nil, class: 'bi bi-arrow-up-short')
    else
      content_tag(:i, nil, class: 'bi bi-arrow-down-short')
    end
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Photo album</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body >

<div class="d-flex flex-column h-100">

  <nav class="navbar bg-light">
    <div class="container-sm">
      <%= link_to 'Photo album', photos_path, class: 'navbar-brand' %>
      <form class="d-flex">
        <%if user_signed_in? %>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %> </li>
            </ul>
          </div>
        <%else %>
          <%= link_to 'Log In', new_user_session_url, class: 'btn btn-dark  btn-lg' %>
        <%end %>
      </form>
    </div>

  </nav>

  <main class="flex-shrink-0">
    <div class="container-sm">
      <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if alert.present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <%= alert %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>


    <div class="container-md">
      <%= yield %>
    </div>
  </main>


  <footer class="footer mt-auto ">
    <div class="container">
      <span class="text-muted"> Last commit: <%= ENV.fetch("RENDER_GIT_COMMIT") { "local" } %></span>
    </div>
  </footer>
</div>

</body>

</html>

app/views/photos/index.html.erb
<h1>Photos</h1>

<% if user_signed_in? %>
  <%= link_to "New photo", new_photo_path, class: "btn btn-primary" %>
<% end %>
<div id="photos">
  <table class="table table-striped table-responsive">
    <thead>
    <tr>
      <th scope="col">#</th>
      <%= sortable_table_header 'Name', :name, :photos_path, class: '' %>
      <%= sortable_table_header 'Uploaded at', :created_at, :photos_path, class: '' %>
      <th>Uploader</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <th scope="row">
          <%= photo.id %>
        </th>
        <td>
          <%= photo.name %>
        </td>
        <td>
          <%= photo.created_at.strftime('%Y-%m-%d %H:%M') %>
        </td>
        <td>
          <%= photo.uploader %>
        </td>
        <td>
          <div class="d-grid gap-2 d-md-flex justify-content-center">
            <%= link_to 'Show', photo.image, class: 'btn btn-outline-success', target: '_blank' %>
            <% if user_signed_in? %>
              <% confirm_text_extra = photo.user == current_user ? '': "Warning! you are deleting someone else's photo!  " %>
              <%= button_to "Delete", photo, method: :delete, class: 'btn btn-danger', data: { turbo_confirm: confirm_text_extra + "Are you sure you want to delete this?" } %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @photos, window: 2, pagination_class: "pagination flex-wrap justify-content-center" %>
</div>

app/views/photos/new.html.erb
<h1>Add new photo</h1>

<%= form_with(model: @photo) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
    <div style="color: red">
      <% if @photo.errors.include?(:name) %>
        <% @photo.errors.full_messages_for(:name).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="mb-3 ">
    <%= form.label :image, class: 'form-label' %>
    <%= form.file_field :image, accept: 'image/png, image/jpeg', class: 'form-control', required: true %>
    <div style="color: red">
      <% if @photo.errors.include?(:image) %>
        <% @photo.errors.full_messages_for(:image).each do |error_message| %>
          <%= error_message %>.
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="d-grid gap-2 d-md-block">
    <%= link_to "Back to photos", photos_path, class: 'btn btn-secondary' %>
    <button type="submit" class="btn btn-primary">Add photo</button>
  </div>

<% end %>